export const actionTypes = {
    PRODUCTS_START: "PRODUCTS_START",
    PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
    PRODUCTS_ERROR: "PRODUCTS_ERROR",
    ADD_TO_CART: "ADD_TO_CART",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
};